const fs = require('fs')
const dir = 'scripts/figma-icons'
const stroked = [
  'arrow-left', 'arrow-right', 'barbell', 'bike', 'building', 'heartbeat', 'home',
  'menu', 'mountain', 'search', 'seeding', 'tree', 'walk', 'yoga', 'yoga-25',
  'calendar', 'chevron-down', 'chevron-right', 'arrows-maximize', 'timer', 'flame',
]
const pascal = (s) => s.split(/[-_ ]/).map((w) => w[0].toUpperCase() + w.slice(1)).join('')

let out = `import type { SVGProps } from 'react'

/**
 * Line icons lifted 1:1 from the Figma file (18/20px grid, 1.5 stroke).
 * Strokes and fills are normalised to \`currentColor\` so one icon serves both
 * the resting (grey-600) and selected (white) tag states.
 *
 * Generated by scripts/gen-icons.cjs from the exported Figma SVGs.
 */
export type IconProps = SVGProps<SVGSVGElement>

`

for (const name of stroked) {
  const src = fs.readFileSync(`${dir}/${name}.svg`, 'utf8')
  const viewBox = src.match(/viewBox="([^"]+)"/)[1]
  let body = src.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim()
  body = body
    .replace(/\sid="[^"]*"/g, '')
    .replace(/stroke="(?!none)[^"]*"/g, 'stroke="currentColor"')
    .replace(/fill="(?!none)[^"]*"/g, 'fill="currentColor"')
    .replace(/stroke-width/g, 'strokeWidth')
    .replace(/stroke-linecap/g, 'strokeLinecap')
    .replace(/stroke-linejoin/g, 'strokeLinejoin')
    .replace(/fill-rule/g, 'fillRule')
    .replace(/clip-rule/g, 'clipRule')
    .replace(/clip-path/g, 'clipPath')
  body = body.split('\n').map((l) => '    ' + l.trim()).filter((l) => l.trim()).join('\n')
  out += `export const ${pascal(name)}Icon = (props: IconProps) => (
  <svg viewBox="${viewBox}" fill="none" aria-hidden="true" focusable="false" {...props}>
${body}
  </svg>
)

`
}
fs.writeFileSync('src/components/icons/line-icons.tsx', out)
console.log('wrote', out.length, 'chars')
