import type { SVGProps } from 'react'

/**
 * Line icons lifted 1:1 from the Figma file (18/20px grid, 1.5 stroke).
 * Strokes and fills are normalised to `currentColor` so one icon serves both
 * the resting (grey-600) and selected (white) tag states.
 *
 * Generated by scripts/gen-icons.cjs from the exported Figma SVGs.
 */
export type IconProps = SVGProps<SVGSVGElement>

export const ArrowLeftIcon = (props: IconProps) => (
  <svg viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M4.16667 10H15.8333M9.16667 5L4.16667 10L9.16667 15" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const ArrowRightIcon = (props: IconProps) => (
  <svg viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M4.16667 10H15.8333M10.8333 5L15.8333 10L10.8333 15" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const BarbellIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M1.5 9H2.25M4.5 6H3C2.80109 6 2.61032 6.07902 2.46967 6.21967C2.32902 6.36032 2.25 6.55109 2.25 6.75V11.25C2.25 11.4489 2.32902 11.6397 2.46967 11.7803C2.61032 11.921 2.80109 12 3 12H4.5M6.75 9H11.25M13.5 6H15C15.1989 6 15.3897 6.07902 15.5303 6.21967C15.671 6.36032 15.75 6.55109 15.75 6.75V11.25C15.75 11.4489 15.671 11.6397 15.5303 11.7803C15.3897 11.921 15.1989 12 15 12H13.5M16.5 9H15.75M4.5 5.25V12.75C4.5 12.9489 4.57902 13.1397 4.71967 13.2803C4.86032 13.421 5.05109 13.5 5.25 13.5H6C6.19891 13.5 6.38968 13.421 6.53033 13.2803C6.67098 13.1397 6.75 12.9489 6.75 12.75V5.25C6.75 5.05109 6.67098 4.86032 6.53033 4.71967C6.38968 4.57902 6.19891 4.5 6 4.5H5.25C5.05109 4.5 4.86032 4.57902 4.71967 4.71967C4.57902 4.86032 4.5 5.05109 4.5 5.25ZM11.25 5.25V12.75C11.25 12.9489 11.329 13.1397 11.4697 13.2803C11.6103 13.421 11.8011 13.5 12 13.5H12.75C12.9489 13.5 13.1397 13.421 13.2803 13.2803C13.421 13.1397 13.5 12.9489 13.5 12.75V5.25C13.5 5.05109 13.421 4.86032 13.2803 4.71967C13.1397 4.57902 12.9489 4.5 12.75 4.5H12C11.8011 4.5 11.6103 4.57902 11.4697 4.71967C11.329 4.86032 11.25 5.05109 11.25 5.25Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const BikeIcon = (props: IconProps) => (
  <svg viewBox="0 0 25 25" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M12.5 19.7917V15.625L9.375 12.5L14.5833 8.33333L16.6667 11.4583H19.7917M8.33333 18.75C8.33333 20.4759 6.93422 21.875 5.20833 21.875C3.48244 21.875 2.08333 20.4759 2.08333 18.75C2.08333 17.0241 3.48244 15.625 5.20833 15.625C6.93422 15.625 8.33333 17.0241 8.33333 18.75ZM22.9167 18.75C22.9167 20.4759 21.5176 21.875 19.7917 21.875C18.0658 21.875 16.6667 20.4759 16.6667 18.75C16.6667 17.0241 18.0658 15.625 19.7917 15.625C21.5176 15.625 22.9167 17.0241 22.9167 18.75ZM18.75 5.20833C18.75 5.78363 18.2836 6.25 17.7083 6.25C17.133 6.25 16.6667 5.78363 16.6667 5.20833C16.6667 4.63304 17.133 4.16667 17.7083 4.16667C18.2836 4.16667 18.75 4.63304 18.75 5.20833Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const BuildingIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M2.25 15.75H15.75M6.75 6H7.5M6.75 9H7.5M6.75 12H7.5M10.5 6H11.25M10.5 9H11.25M10.5 12H11.25M3.75 15.75V3.75C3.75 3.35218 3.90804 2.97064 4.18934 2.68934C4.47064 2.40804 4.85218 2.25 5.25 2.25H12.75C13.1478 2.25 13.5294 2.40804 13.8107 2.68934C14.092 2.97064 14.25 3.35218 14.25 3.75V15.75" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const HeartbeatIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M14.625 10.179L8.99998 15.75L6.82798 13.599M2.24023 7.521C2.23396 6.73002 2.47797 5.95731 2.93737 5.31338C3.39676 4.66945 4.04802 4.18727 4.79799 3.93581C5.54796 3.68435 6.35824 3.67648 7.11296 3.91333C7.86767 4.15018 8.52816 4.61961 8.99998 5.2545C9.31013 4.84201 9.70208 4.49799 10.1513 4.24395C10.6005 3.98991 11.0974 3.83133 11.6107 3.77814C12.124 3.72494 12.6428 3.77827 13.1346 3.93479C13.6263 4.09131 14.0805 4.34765 14.4686 4.68777C14.8568 5.02789 15.1705 5.44446 15.3903 5.91142C15.61 6.37837 15.731 6.88566 15.7457 7.40153C15.7604 7.9174 15.6684 8.43074 15.4756 8.90944C15.2827 9.38813 14.9932 9.82186 14.625 10.1835M2.25 9.75H3.75L5.25 12L6.75 7.5L7.5 9.75H9.75" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const HomeIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M6.75 15.75V11.25C6.75 10.8522 6.90804 10.4706 7.18934 10.1893C7.47064 9.90804 7.85218 9.75 8.25 9.75H9.75C10.1478 9.75 10.5294 9.90804 10.8107 10.1893C11.092 10.4706 11.25 10.8522 11.25 11.25V15.75M3.75 9H2.25L9 2.25L15.75 9H14.25V14.25C14.25 14.6478 14.092 15.0294 13.8107 15.3107C13.5294 15.592 13.1478 15.75 12.75 15.75H5.25C4.85218 15.75 4.47064 15.592 4.18934 15.3107C3.90804 15.0294 3.75 14.6478 3.75 14.25V9Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const MenuIcon = (props: IconProps) => (
  <svg viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M4 8H20M4 16H20" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const MountainIcon = (props: IconProps) => (
  <svg viewBox="0 0 25 25" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M7.8125 11.4583L9.89583 14.0625L12.5 11.4583L14.5833 14.5833L17.1875 12.5M3.125 20.8333H21.875L14.6656 5.6125C14.4715 5.20234 14.165 4.85572 13.7816 4.61299C13.3982 4.37027 12.9538 4.2414 12.5 4.2414C12.0462 4.2414 11.6018 4.37027 11.2184 4.61299C10.835 4.85572 10.5285 5.20234 10.3344 5.6125L3.125 20.8333Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const SearchIcon = (props: IconProps) => (
  <svg viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const SeedingIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M9 9H6.75C5.55653 9 4.41193 8.52589 3.56802 7.68198C2.72411 6.83807 2.25 5.69347 2.25 4.5V3H4.5C5.69347 3 6.83807 3.47411 7.68198 4.31802C8.52589 5.16193 9 6.30653 9 7.5V15M9 10.5C9 9.30653 9.47411 8.16193 10.318 7.31802C11.1619 6.47411 12.3065 6 13.5 6H15.75V6.75C15.75 7.94347 15.2759 9.08807 14.432 9.93198C13.5881 10.7759 12.4435 11.25 11.25 11.25H9" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const TreeIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M9 9.75L7.5 8.25M9 9L10.5 7.5M9 15.75V6M7.36799 11.9963C7.03985 11.9771 6.71989 11.8862 6.43064 11.7301C6.14139 11.5739 5.88987 11.3563 5.69377 11.0925C5.49767 10.8287 5.36175 10.5251 5.29557 10.2031C5.2294 9.88113 5.23458 9.54856 5.31074 9.2288C5.03855 9.00255 4.82362 8.71524 4.68343 8.39024C4.54324 8.06525 4.48176 7.71175 4.50398 7.35851C4.5262 7.00526 4.63149 6.66225 4.8113 6.35739C4.99111 6.05252 5.24035 5.79441 5.53874 5.60405C5.27727 5.13954 5.18921 4.59729 5.29024 4.0739C5.39127 3.55052 5.67484 3.08001 6.09042 2.7462C6.50599 2.41238 7.02659 2.23695 7.55944 2.25117C8.0923 2.26538 8.6028 2.46831 8.99999 2.8238C9.39728 2.46887 9.90761 2.26642 10.4402 2.25249C10.9727 2.23855 11.4929 2.41403 11.9082 2.74769C12.3235 3.08136 12.607 3.55156 12.7081 4.07461C12.8092 4.59766 12.7215 5.13963 12.4605 5.60405C12.7591 5.79424 13.0085 6.05226 13.1885 6.3571C13.3684 6.66194 13.4739 7.00498 13.4962 7.35828C13.5185 7.71158 13.457 8.06515 13.3168 8.3902C13.1766 8.71525 12.9615 9.00258 12.6892 9.2288C12.768 9.55939 12.7708 9.90353 12.6975 10.2354C12.6242 10.5672 12.4767 10.8781 12.266 11.1448C12.0553 11.4115 11.787 11.627 11.4811 11.7751C11.1753 11.9232 10.8398 12.0001 10.5 12H10.5007H7.50074L7.36799 11.9963Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const WalkIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M5.25 15.75L7.5 12.75M12 15.75L10.5 12.75L8.25 10.5L9 6M13.5 9L11.25 8.25L9 6L6 6.75L4.5 9M10.5 3C10.5 3.41421 10.1642 3.75 9.75 3.75C9.33579 3.75 9 3.41421 9 3C9 2.58579 9.33579 2.25 9.75 2.25C10.1642 2.25 10.5 2.58579 10.5 3Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const YogaIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M10.9283 11.253L11.5717 12.6368C11.5717 12.6368 14.4645 13.251 14.4645 14.712C14.4645 15.75 13.1775 15.75 13.1775 15.75H9.75L8.0625 14.8125" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    <path d="M7.07175 11.253L6.429 12.6368C6.429 12.6368 3.5355 13.251 3.5355 14.712C3.5355 15.75 4.8225 15.75 4.8225 15.75H6.375L8.0625 14.8125L10.125 13.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    <path d="M2.25 11.9445C2.25 11.9445 3.85725 11.5987 4.82175 11.253C5.7855 6.4095 8.6775 6.75525 9 6.75525C9.32175 6.75525 12.2145 6.4095 13.1782 11.253C14.1427 11.598 15.75 11.9445 15.75 11.9445M9 5.25C9.39782 5.25 9.77936 5.09196 10.0607 4.81066C10.342 4.52936 10.5 4.14782 10.5 3.75C10.5 3.35218 10.342 2.97064 10.0607 2.68934C9.77936 2.40804 9.39782 2.25 9 2.25C8.60218 2.25 8.22064 2.40804 7.93934 2.68934C7.65804 2.97064 7.5 3.35218 7.5 3.75C7.5 4.14782 7.65804 4.52936 7.93934 4.81066C8.22064 5.09196 8.60218 5.25 9 5.25Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const Yoga25Icon = (props: IconProps) => (
  <svg viewBox="0 0 25 25" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M15.1781 15.6292L16.0719 17.551C16.0719 17.551 20.0896 18.4042 20.0896 20.4333C20.0896 21.875 18.3021 21.875 18.3021 21.875H13.5417L11.1979 20.5729" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    <path d="M9.82187 15.6292L8.92917 17.551C8.92917 17.551 4.91042 18.4042 4.91042 20.4333C4.91042 21.875 6.69792 21.875 6.69792 21.875H8.85417L11.1979 20.5729L14.0625 18.75" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    <path d="M3.125 16.5896C3.125 16.5896 5.35729 16.1094 6.69687 15.6292C8.03542 8.90208 12.0521 9.38229 12.5 9.38229C12.9469 9.38229 16.9646 8.90208 18.3031 15.6292C19.6427 16.1083 21.875 16.5896 21.875 16.5896M12.5 7.29167C13.0525 7.29167 13.5824 7.07217 13.9731 6.68147C14.3638 6.29077 14.5833 5.76087 14.5833 5.20833C14.5833 4.6558 14.3638 4.12589 13.9731 3.73519C13.5824 3.34449 13.0525 3.125 12.5 3.125C11.9475 3.125 11.4176 3.34449 11.0269 3.73519C10.6362 4.12589 10.4167 4.6558 10.4167 5.20833C10.4167 5.76087 10.6362 6.29077 11.0269 6.68147C11.4176 7.07217 11.9475 7.29167 12.5 7.29167Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const CalendarIcon = (props: IconProps) => (
  <svg viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M13.3333 2.5V5.83333M6.66667 2.5V5.83333M3.33333 9.16667H16.6667M5 4.16667H15C15.9205 4.16667 16.6667 4.91286 16.6667 5.83333V15.8333C16.6667 16.7538 15.9205 17.5 15 17.5H5C4.07953 17.5 3.33333 16.7538 3.33333 15.8333V5.83333C3.33333 4.91286 4.07953 4.16667 5 4.16667Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const ChevronDownIcon = (props: IconProps) => (
  <svg viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M5 7.5L10 12.5L15 7.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const ChevronRightIcon = (props: IconProps) => (
  <svg viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M7.5 5L12.5 10L7.5 15" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const ArrowsMaximizeIcon = (props: IconProps) => (
  <svg viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M16.6667 6.66667V3.33333H13.3333M16.6667 3.33333L11.6667 8.33333M3.33333 13.3333V16.6667H6.66667M3.33333 16.6667L8.33333 11.6667M16.6667 13.3333V16.6667H13.3333M16.6667 16.6667L11.6667 11.6667M3.33333 6.66667V3.33333H6.66667M3.33333 3.33333L8.33333 8.33333" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

export const TimerIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <g>
    <path d="M5.33333 1.33333H10.6667" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M8 9V6.33333" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
    <path d="M8 3.75C10.8995 3.75 13.25 6.1005 13.25 9C13.25 11.8995 10.8995 14.25 8 14.25C5.1005 14.25 2.75 11.8995 2.75 9C2.75 6.1005 5.1005 3.75 8 3.75Z" stroke="currentColor" strokeWidth="1.5"/>
    </g>
    </g>
  </svg>
)

export const FlameIcon = (props: IconProps) => (
  <svg viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
    <g>
    <path d="M10 10C11.6667 7.53333 10 4.16667 9.16667 3.33333C9.16667 5.865 7.68917 7.28417 6.66667 8.33333C5.645 9.38333 5 11.0333 5 12.5C5 13.8261 5.52678 15.0979 6.46447 16.0355C7.40215 16.9732 8.67392 17.5 10 17.5C11.3261 17.5 12.5979 16.9732 13.5355 16.0355C14.4732 15.0979 15 13.8261 15 12.5C15 11.2233 14.12 9.21667 13.3333 8.33333C11.845 10.8333 11.0075 10.8333 10 10Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </g>
  </svg>
)

